"""Atualizar modelos

Revision ID: f6b719f12db4
Revises: e25a98968b11
Create Date: 2023-12-18 09:58:11.303193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b719f12db4'
down_revision = 'e25a98968b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('quilometragem', sa.Float(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carro_id'), ['id'], unique=False)

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index('ix_produto_id')

    op.drop_table('produto')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carro_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_pedido_produto', type_='foreignkey')
        batch_op.create_foreign_key('fk_pedido_carro', 'carro', ['carro_id'], ['id'])
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_pedido_carro', type_='foreignkey')
        batch_op.create_foreign_key('fk_pedido_produto', 'produto', ['produto_id'], ['id'])
        batch_op.drop_column('carro_id')

    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('detalhes', sa.VARCHAR(), nullable=True),
    sa.Column('preco', sa.FLOAT(), nullable=True),
    sa.Column('disponivel', sa.BOOLEAN(), nullable=True),
    sa.Column('tamanhos', sa.VARCHAR(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index('ix_produto_id', ['id'], unique=False)

    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carro_id'))

    op.drop_table('carro')
    # ### end Alembic commands ###
